#!/bin/bash - 

# Zeroman Yang (51feel@gmail.com)
# 10/17/2015

set -e

cur_path=$(readlink -f $0)
cur_dir=${cur_path%/*}

SUDO=$(test "$(id -u)" = "0" || which sudo || true)


proc_css_file()
{
    local csspath=$1
    local outputdir=$2

    if [ ! -e "$csspath" ];then
        csspath="common/css/modern.css"
    fi
    if [ -e "$csspath" ];then
        mkdir -p $outputdir/css
        cp -rf $csspath $outputdir/css
    else
        csspath=""
    fi
    echo $csspath
}

source2tex()
{
    local srcfile=$1
    local texfile=$2

    > $texfile
    ext=${srcfile##*.}
    case $ext in
        py)
            echo '\begin{python}' >> $texfile
            cat $srcfile >> $texfile
            echo '\end{python}' >> $texfile
            ;;
        c|h|cpp|C|H|CPP)
            echo '\begin{cpp}' >> $texfile
            cat $srcfile >> $texfile
            echo '\end{cpp}' >> $texfile
            ;;
        *)
            echo '\begin{lstlisting}[language={[ANSI]C}]' >> $texfile
            cat $srcfile >> $texfile
            echo '\end{lstlisting}' >> $texfile
            ;;
    esac
}

source2html()
{
    local srcfile=$1
    local htmlfile=$2

    echo "<pre>" > $htmlfile
    highlight --inline-css -f $srcfile >> $htmlfile
    echo "</pre>" >> $htmlfile
}

convert2html()
{
    local t2tfile=$1
    local outputdir=$2
    local css=$3

    local inputdir=$(dirname $t2tfile)
    local options="-t html"
    options+=" --encoding=utf-8"
    options+=" --toc"
    options+=" --toc-level 3"
    options+=" --config-file=$cur_dir/common/config.t2t"

    local cssfile="$(proc_css_file common/css/${css}.css $outputdir)"
    test -e "$cssfile" && options+=" --css-sugar --style=$cssfile"

    local t2tname=$(basename $t2tfile)
    local htmlfile=$(readlink -m $outputdir/${t2tname/.t2t}.html)

    newt2tfile=$outputdir/$t2tname
    cp -f $t2tfile $newt2tfile
    for srcfile in $(ls $inputdir/*.{c,cpp,h,C,CPP,H,py} 2>/dev/null)
    do
        source2html $srcfile $outputdir/$(basename $srcfile).html
        srcfilename=$(basename $srcfile)
        sed -i "s#$srcfilename'#$srcfilename.html'#g" $newt2tfile
    done

    mkdir -p $outputdir
    test -d "$inputdir/img" && cp -rf $inputdir/img $outputdir
    test -d "$inputdir/css" && cp -rf $inputdir/css $outputdir
    echo "txt2tags $options -o $htmlfile $newt2tfile"
    txt2tags $options -o $htmlfile $newt2tfile
}

convert2tex()
{
    local t2tfile=$1
    local outputdir=$2

    local options="-t tex"
    options+=" --encoding=utf-8"
    options+=" --toc"
    options+=" --toc-level 3"
    options+=" --style $cur_dir/common/sty/zmnote.sty"
    options+=" --style $cur_dir/common/sty/zhtexfont.sty"
    options+=" --style $cur_dir/common/sty/cpphighlight.sty"
    options+=" --style $cur_dir/common/sty/pythonhighlight.sty"
    options+=" --config-file=$cur_dir/common/config.t2t"

    local t2tname=$(basename $t2tfile)
    local inputdir=$(dirname $t2tfile)
    local texfile=$(readlink -m $outputdir/${t2tname/.t2t}.tex)

    mkdir -p $outputdir
    newt2tfile=$outputdir/$t2tname
    cp -f $t2tfile $newt2tfile
    for srcfile in $(ls $inputdir/*.{c,cpp,h,C,CPP,H,py} 2>/dev/null)
    do
        source2tex $srcfile $outputdir/$(basename $srcfile).tex
        srcfilename=$(basename $srcfile)
        sed -i "s#$srcfilename'#$srcfilename.tex'#g" $newt2tfile
    done

    echo "txt2tags $options -o $texfile $newt2tfile"
    txt2tags $options -o $texfile $newt2tfile
}

convert2pdf()
{
    local t2tfile=$1
    local outputdir=$2

    local inputdir=$(dirname $t2tfile)
    local t2tname=$(basename $t2tfile)
    local texfile=$(readlink -m $outputdir/${t2tname/.t2t}.tex)
    local pdffile=$(readlink -m $outputdir/${t2tname/.t2t}.pdf)

    echo "convert $t2tfile to $pdffile"

    mkdir -p $outputdir

    convert2tex $t2tfile $outputdir

    test -d $inputdir/img && mkdir -p $outputdir/img
    for img in $(find $inputdir/img/ -type f)
    do
        imgname=$(basename $img)
        convert $img $outputdir/img/${imgname/.*}.eps
    done

    cd $outputdir
    xelatex ${texfile}
    xelatex ${texfile}                         # genarate index
    cd $cur_dir
}

convert_dir()
{
    local inputdir=$1
    local outputdir=$2
    local converttype=$3

    if [ -e "$inputdir/main.t2t" ];then
        convert${converttype} $inputdir/main.t2t $outputdir 
    else
        for t2tfile in $(ls $inputdir/*.t2t 2>/dev/null)
        do
            local t2tname=$(basename $t2tfile)
            convert2${converttype} $t2tfile $outputdir 
        done
    fi
}

convert_all()
{
    local inputdir=$1
    local outputdir=$2
    local converttype=$3

    if [ ! -d "$inputdir" ];then
        return
    fi

    t2tdirs=$(cd $inputdir;find . -type d ! -name '*.git')
    for dir in $t2tdirs
    do
        convert_dir "$(readlink -m $inputdir/$dir)" "$(readlink -m $outputdir/$dir)" $converttype
    done
}

convert_test()
{
    local test_dir="test"
    convert_all $test_dir output/html html
    convert_all $test_dir output/tex tex
    convert_all $test_dir output/pdf pdf

    echo ""
    find output/html -name '*.html'
    find output/tex -name '*.tex'
    find output/pdf -name '*.pdf'
}

install_zm_note()
{
    local installdir=$1    
    
    if [ -z "$installdir" ];then
        installdir="/usr/share/zm-note"
    fi

    $SUDO mkdir -p $installdir
    $SUDO cp -rf $cur_dir/{zm-note,common,css,test} $installdir/
    $SUDO mkdir -p $_root_dir/usr/bin
    $SUDO ln -svf /usr/share/zm-note/zm-note $_root_dir/usr/bin/zm-note
}

case $1 in
    -t|--test)
        convert_test
        ;;
    -i|--install)
        shift
        install_zm_note $1
        ;;
    *)
        format=$1
        inputdir=$2
        outputdir=$3
        if [ -d "$inputdir" -a -n "$outputdir" -a -n "$format" ];then
            convert_all $inputdir $outputdir $format
        else
            echo "$0 format inputdir outputdir"
        fi
        ;;
esac

