#!/bin/bash - 

# Zeroman Yang (51feel@gmail.com)
# 10/17/2015

set -e

cur_path=$(readlink -f $0)
cur_dir=${cur_path%/*}

proc_css_file()
{
    local csspath=$1
    local outputdir=$2

    if [ ! -e "$csspath" ];then
        csspath="css/modern.css"
    fi
    if [ -e "$csspath" ];then
        mkdir -p $outputdir/css
        cp -rf $csspath $outputdir/css
    else
        csspath=""
    fi
    echo $csspath
}

convert2html()
{
    local t2tfile=$1
    local outputdir=$2
    local css=$3
    local configfile=$4

    local inputdir=$(dirname $t2tfile)
    local options="-t html"
    options+=" --encoding=utf-8"
    options+=" --toc"
    options+=" --toc-level 3"

    local cssfile="$(proc_css_file css/${css}.css $outputdir)"
    test -e "$cssfile" && options+=" --css-sugar --style=$cssfile"
    test -e "$configfile" && options+=" --config-file=$configfile"

    local t2tname=$(basename $t2tfile)
    local htmlfile=$(readlink -m $outputdir/${t2tname/.t2t}.html)

    mkdir -p $outputdir
    test -d "$inputdir/img" && cp -rf $inputdir/img $outputdir
    test -d "$inputdir/css" && cp -rf $inputdir/css $outputdir
    echo "txt2tags $options -o $htmlfile $t2tfile"
    txt2tags $options -o $htmlfile $t2tfile
}

convert2tex()
{
    local t2tfile=$1
    local outputdir=$2
    local configfile=$3

    local options="-t tex"
    options+=" --encoding=utf-8"
    options+=" --toc"
    options+=" --toc-level 3"

    local cssfile="$(proc_css_file css/${css}.css $outputdir)"
    test -e "$configfile" && options+=" --config-file=$configfile"

    local t2tname=$(basename $t2tfile)
    local texfile=$(readlink -m $outputdir/${t2tname/.t2t}.tex)

    mkdir -p $outputdir
    echo "txt2tags $options -o $texfile $t2tfile"
    txt2tags $options -o $texfile $t2tfile
}

convert2pdf()
{
    local t2tfile=$1
    local outputdir=$2

    local inputdir=$(dirname $t2tfile)
    local t2tname=$(basename $t2tfile)
    local texfile=$(readlink -m $outputdir/${t2tname/.t2t}.tex)
    local pdffile=$(readlink -m $outputdir/${t2tname/.t2t}.pdf)

    echo "convert $t2tfile to $pdffile"

    mkdir -p $outputdir

    convert2tex $t2tfile $outputdir common/config.t2t

    cp -f common/zhtexfont.sty $outputdir
    test -d $inputdir/img && mkdir -p $outputdir/img
    for img in $(find $inputdir/img/ -type f)
    do
        imgname=$(basename $img)
        convert $img $outputdir/img/${imgname/.*}.eps
    done

    cd $outputdir
    xelatex ${texfile}
    xelatex ${texfile}                         # genarate index
    cd $cur_dir
}

convert_dir()
{
    local inputdir=$1
    local outputdir=$2
    local converttype=$3

    if [ -e "$inputdir/main.t2t" ];then
        convert${converttype} $inputdir/main.t2t $outputdir 
    else
        for t2tfile in $(find $inputdir -maxdepth 1 -name *.t2t)
        do
            local t2tname=$(basename $t2tfile)
            convert2${converttype} $t2tfile $outputdir 
        done
    fi
}

convert_all()
{
    local inputdir=$1
    local outputdir=$2
    local converttype=$3

    if [ ! -d "$inputdir" ];then
        return
    fi

    t2tdirs=$(cd $inputdir;find . -type d ! -name *.git)
    for dir in $t2tdirs
    do
        convert_dir $inputdir/$dir $outputdir/$dir $converttype
    done
}

convert_test()
{
    local test_dir="test"
    convert_all $test_dir output/html html
    convert_all $test_dir output/tex tex
    convert_all $test_dir output/pdf pdf

    echo ""
    find output/html -name *.html 
    find output/tex -name *.tex
    find output/pdf -name *.pdf 
}


case $1 in
    -t|--test)
        convert_test
        ;;
    *)
        format=$1
        inputdir=$2
        outputdir=$3
        if [ -d "$inputdir" -a -n "$outputdir" -a -n "$format" ];then
            convert_all $inputdir $outputdir $format
        else
            echo "$0 format inputdir outputdir"
        fi
        ;;
esac

